import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'MinYeo Projects',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko-kr">
      <body className={inter.className}>{children}</body>
      {/* <footer>풋터</footer> */}
    </html>
  )
}
